### ISSUE TITLE
Change button name

### ISSUE THREAD

**Issue by vaishnavipandey-vp** [Basecamp-Community/Web-Development#11]
Change F button to **Celsius to Fahrenheit** and C button to **Fahrenheit to Celsius** in index.html

**Comment by amino19** [comment]
Hey @vaishnavipandey-vp, nice to have you here, but this issue is already taken by me, & get changes over it. I think as of basics we all prefer "F" for Farenheit in temperature & "C" for Celcius. So, pl look around some more features to add on.
Hope you'll go through it.

**Comment by vaishnavipandey-vp** [comment]
Okay @amino19 I'll surely go through it.
