### ISSUE TITLE
FIX: Change Title

### ISSUE THREAD

**Issue by mindninjaX** [Basecamp-Community/Web-Development#3]
Replace the title from '**Fahrenheit - Celsius Converter'** to '**Temperature Converter**' in the index.html

![image](https://user-images.githubusercontent.com/59148052/112596150-6f7df700-8e31-11eb-8ef1-df2c543323a8.png)

**Comment by rukshan99** [comment]
Can I work on this?

**Comment by mindninjaX** [comment]
Thank you for your interest in the issue... Yes please go ahead and make the changes & I am assigning you this issue
