### ISSUE TITLE
Lets work on Background!

### ISSUE THREAD

**Issue by amino19** [Basecamp-Community/Web-Development#7]
Going to add a sort of code :
``` 
body {
  background-image: url("gify.gif");
}
```

**Preview :**
Also gives more padding to the site, & similar colours, so, it doesn't looks distinct.

![Screenshot (801)](https://user-images.githubusercontent.com/75872316/112732852-807a5580-8f62-11eb-9bff-9d118171acff.png)

Can I proceed?

**Comment by surajondev** [comment]
Yes, you can work on the background.

Go on with the pull request

**Comment by amino19** [comment]
Changes are all set, check it out & merge.

**Comment by mindninjaX** [comment]
We have successfully merged your PR! Thanks for your work! Highly appreciate it!
